services:
  bot:
    build: .
    volumes:
      - .:/app
    expose:
      - 80
    networks:
      default:
        aliases:
          - web_internal
      traefik:

    labels: # new
      - "traefik.enable=true"
      - "traefik.http.routers.bot.entrypoints=https"
      - "traefik.http.routers.bot.rule=Host(`old.kik-soft.ru`)"
      - "traefik.http.routers.bot.tls=true"
      - "traefik.http.routers.bot.tls.certresolver=letsEncrypt"
      - "traefik.http.services.bot-service.loadbalancer.server.port=80"
  zulip_listen:
    build:
      context: . #/app
      dockerfile: Dockerfile_z_l
    volumes:
      - .:/app
    expose:
      - 80
    labels:
      - "traefik.enable=true"
networks:
  traefik:
    name: traefik
    external: true